import {
  StyleSheet, Dimensions, Platform,
} from 'react-native';
import Constants from 'expo-constants';

const TABBAR_WIDTH = Dimensions.get('window').width;
const TAB_WIDTH = TABBAR_WIDTH / 5;

// eslint-disable-next-line no-unused-vars
export default StyleSheet.create({
  /* health styles */
  petCard: {
    height: 200,
    width: 160,
    backgroundColor: 'white',
    color: '#333333',
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 0,
    paddingBottom: 10,
    justifyContent: 'flex-end',
    alignItems: 'center',
    alignSelf: 'center',
    margin: 10,
    marginTop: 0,
    marginBottom: -30,
    borderRadius: 25,
  },

  shadowProp: {
    shadowColor: '#333333',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },

  petHeader: {
    fontSize: 32,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 5,
    fontFamily: 'QuicksandBold',
    color: '#333333',
  },

  petImage: {
    height: 135,
    width: 135,
    borderRadius: 100,
    borderWidth: 3,
    borderColor: '#e0777d',
  },

  healthContainer: {
    alignSelf: 'center',
    width: (Dimensions.get('window').width - 20),
    backgroundColor: 'white',
    borderRadius: 25,
    overflow: 'hidden',
    marginBottom: 20,
  },

  healthHeader: {
    fontSize: 20,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    alignSelf: 'center',
    marginTop: 15,
    marginBottom: 5,
    fontFamily: 'QuicksandBold',
    color: '#333333',
  },
  /* services styles */
  servImage: {
    height: 160,
    width: 95,
    top: -30,
    left: -5,
    justifyContent: 'center',
    borderWidth: 3,
    borderRadius: 25,
    alignSelf: 'center',
    position: 'absolute',
    borderColor: '#e0777d',
  },

  servLeft: {
    height: 160,
    width: 90,
    borderRightWidth: 3,
    position: 'absolute',
    justifyContent: 'center',
    alignContent: 'center',
    borderColor: '#e0777d',
  },

  servCheck: {
    height: 25,
    width: 90,
    top: 100,
    position: 'absolute',
    borderRightWidth: 3,
    borderTopWidth: 3,
    backgroundColor: 'white',
    borderColor: '#e0777d',
  },
  servContainer: {
    alignSelf: 'center',
    width: (Dimensions.get('window').width - 20),
    backgroundColor: 'white',
    borderRadius: 25,
    overflow: 'hidden',
    marginBottom: 20,
  },

  servHeader: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 1,
    marginLeft: 105,
    marginTop: 5,
    fontFamily: 'QuicksandBold',
    color: '#333333',
  },

  servHeader2: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1,
    marginLeft: 105,
    fontFamily: 'QuicksandBold',
    color: '#333333',
  },

  servStar1: {
    marginLeft: 260,
    marginTop: 10,
    position: 'absolute',
  },

  servStar2: {
    marginLeft: 280,
    marginTop: 10,
    position: 'absolute',
  },

  servStar3: {
    marginLeft: 300,
    marginTop: 10,
    position: 'absolute',
  },

  servStar4: {
    marginLeft: 320,
    marginTop: 10,
    position: 'absolute',
  },

  servStar5: {
    marginLeft: 340,
    marginTop: 10,
    position: 'absolute',
  },
  /* PawPic styles */
  picImage: {
    height: 300,
    width: (Dimensions.get('window').width - 18),
    top: 0,
    left: 0,
    justifyContent: 'center',
    borderRadius: 25,
    alignSelf: 'center',
    position: 'absolute',
  },

  picContainer: {
    alignSelf: 'center',
    width: (Dimensions.get('window').width - 20),
    backgroundColor: 'white',
    borderRadius: 25,
    overflow: 'hidden',
    marginBottom: 20,
  },

  ppProfileImage: {
    height: 60,
    width: 60,
    top: 245,
    left: 0,
    borderRadius: 100,
    borderWidth: 3,
    position: 'absolute',
    borderColor: '#e0777d',
  },

  ppProfileNameNode: {
    height: 25,
    width: 160,
    top: 275,
    left: 37.5,
    borderRadius: 100,
    borderWidth: 3,
    justifyContent: 'center',
    position: 'absolute',
    borderColor: '#e0777d',
    backgroundColor: 'white',
  },

  picHeader: {
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 1,
    marginLeft: 105,
    marginTop: 5,
    fontFamily: 'QuicksandBold',
    color: '#333333',
  },

  picHeader2: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1,
    marginLeft: 20,
    fontFamily: 'QuicksandBold',
    color: '#333333',
  },
  /* news/events styles */
  eventTab: {
    alignSelf: 'center',
    height: 'auto',
    width: Dimensions.get('window').width - 30,
    backgroundColor: 'white',
    borderRadius: 50,
    overflow: 'hidden',
    padding: 35,
    paddingBottom: 30,
    paddingTop: 25,
    marginRight: 15,
    marginLeft: 15,
  },
  eventHeader: {
    fontFamily: 'QuicksandBold',
    fontSize: 26,
  },
  eventDate: {
    fontFamily: 'QuicksandSemiBold',
    fontSize: 20,
    paddingTop: 5,
  },
  eventText: {
    fontFamily: 'QuicksandRegular',
    fontSize: 20,
    paddingLeft: 5,
    paddingRight: 30,
    textAlign: 'justify',
  },
  newsTab: {
    alignSelf: 'center',
    marginTop: 20,
    height: 'auto',
    width: Dimensions.get('window').width - 30,
    backgroundColor: 'white',
    borderRadius: 50,
    overflow: 'hidden',
    padding: 35,
    paddingBottom: 30,
    paddingTop: 25,
    marginRight: 15,
    marginLeft: 15,
  },
  newsHeader: {
    fontFamily: 'QuicksandBold',
    fontSize: 26,
    textAlign: 'center',
  },
  /* map styles */
  containerMap: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    padding: 8,
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  search: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    justifyContent: 'space-between',
    flex: 1,
  },
  container: {
    margin: 15,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    width: '90%',
    justifyContent: 'space-between',
  },
  searchBar: {
    padding: 10,
    flexDirection: 'row',
    marginRight: 40,
    width: 45,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 150,
    elevation: 24,
  },
  input: {
    fontSize: 20,
    marginLeft: 10,
    width: '90%',
  },
  filters: {
    position: 'absolute',
    marginLeft: 50,
    height: 45,
    width: 45,
    flex: 1,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 22.5,
    right: -5,
    elevation: 20,
  },
  modalView: {
    margin: 15,
    flexDirection: 'row',
    // alignItems: 'center',
    padding: 45,
    width: '90%',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 24,
  },
  tabBarContainer: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    position: 'absolute',
    width: Dimensions.get('window').width + 6,
    height: Platform.OS === 'ios' ? 80 : 73,
    borderRadius: 5,
    zIndex: 5,
    // borderWidth: 4,
    borderColor: 'rgba(158, 150, 150, .25)',
    bottom: -5,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 100,
    shadowRadius: 20,
    elevation: 24,
  },
  circleAnimated: {
    width: TAB_WIDTH,
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  circle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#FFFFFF',
    bottom: 30,
    borderWidth: 0,
    borderColor: '#69A297', // all pages will be one color so,,, just set it to that color
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 100,
    shadowRadius: 20,
    elevation: 24,
  },
  circle2: {
    position: 'absolute',
    width: 95,
    height: 95,
    borderRadius: 47.5,
    backgroundColor: '#FFFFFF',
    bottom: Platform.OS === 'ios' ? 16 : 8,
    borderWidth: 7,
    borderColor: '#69A297',
    elevation: 24,
  },
  pawPupPic: {
    position: 'absolute',
    flex: 1,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 12,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    marginLeft: (((Dimensions.get('window').width) / 5) * 3.5) - 81,
    bottom: Platform.OS === 'ios' ? 102 : 85,
    borderWidth: 7,
    borderColor: '#69A297',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  pawPupPost: {
    position: 'absolute',
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginLeft: (((Dimensions.get('window').width) / 5) * 3.5) - 25, // 55 normally
    bottom: Platform.OS === 'ios' ? 127 : 110, // 0 normally
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 12,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 7,
    borderColor: '#69A297',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  pawPupPM: {
    position: 'absolute',
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginLeft: (((Dimensions.get('window').width) / 5) * 3.5) + 32,
    bottom: Platform.OS === 'ios' ? 102 : 85,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 12,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 7,
    borderColor: '#69A297',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalView1: {
    justifyContent: 'space-evenly',
    backgroundColor: '#FFFFF',
    alignSelf: 'center',
  },
  pawPupHealth: {
    position: 'absolute',
    flex: 1,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 12,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    marginLeft: (((Dimensions.get('window').width) / 5) * 4.5) - 95,
    bottom: Platform.OS === 'ios' ? 92 : 75,
    borderWidth: 7,
    borderColor: '#69A297',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  pawPupAccount: {
    position: 'absolute',
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginLeft: (((Dimensions.get('window').width) / 5) * 4.5) - 55, // 55 normally
    bottom: Platform.OS === 'ios' ? 122 : 105, // 0 normally
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 12,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 7,
    borderColor: '#69A297',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  pawPupSettings: {
    position: 'absolute',
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginLeft: (((Dimensions.get('window').width) / 5) * 4.5) - 5,
    bottom: Platform.OS === 'ios' ? 123 : 106,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 12,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 7,
    borderColor: '#69A297',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
});
